name: Linters, Spellcheck, and Tests

on:
  push:
    paths:
      - '**.go'
  workflow_dispatch:

jobs:
  LintnTest:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install dependencies
        run: make installpkgs
      - name: Run linters
        run: make lint
      - name: Run tests
        run: make test

  Spellcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.29.7
